### ISSUE TITLE
Accepting method arguments

### ISSUE THREAD

**Issue by nilbus** [rspec/rspec-its#19]
Before I implement this, I should ask - would you accept a patch that passes arguments to the method?

``` ruby
subject { MathExample.new }
describe '#root' do
  its(:root, 9) { should == 3 }
  its(:root, 16) { should == 4 }
end
```

What do you think? Is this against the philosophy of the simplicity and readability of `its`? This is a short example, but I find myself wanting to do this where I have lots of short examples with different fixed inputs to a method. This is a lot more concise than the alternative:

``` ruby
subject(:math) { MathExample.new }
describe '#root' do
  it 'finds the square root of 9' do
    expect(math).root(9).to eq 3
  end

  it 'finds the square root of 16' do
    expect(math).root(16).to eq 4
  end
end
```

**Comment by d-Pixie** [comment]
Nice trick to accomplish this with the gem as is:

```
RSpec.describe Range do
  let(:range) { described_class.new( 1, 10 )}

  describe '#cover?' do
    subject { range.method(:cover?) }

    its([2]) { is_expected.to eq true }
    its([1..4]) { is_expected.to eq true }
  end
end
```

Unfortunately not my idea 🙂  All credit goes to https://zverok.github.io/blog/2017-11-01-rspec-method-call.html

**Comment by pirj** [comment]
Another option that doesn't involve `rspec-its`:
```ruby
describe '#root' do
  def root(x)
    MathExample.new.root(x)
  end

  it { expect(root(16)).to eq 4 }
  it { expect(root(9)).to eq 3 }
end
```

```ruby
RSpec.describe Range do
  subject(:range) { described_class.new( 1, 10 )}

  describe '#cover?' do
    def cover?(range_or_value)
      range.cover?(range_or_value)
    end

    it { expect(cover?(2)).to be(true) }
    it { expect(cover?(1..4)).to be(true) }
  end
end
```

All credit goes to the Effective Testing with RSpec 3 book.
