### ISSUE TITLE
Please update to compatible with RSpec 3.2

### ISSUE THREAD

**Issue by otg-kalex** [rspec/rspec-its#38]
```
  In Gemfile:
    rspec-rails (>= 3.2.0) ruby depends on
      rspec-core (~> 3.2.0) ruby

    rspec-its (>= 1.2.0) ruby depends on
      rspec-core (3.1.7)
```

**Comment by jamesottaway** [comment]
[According to `rspec-its` on rubygems.org](https://rubygems.org/gems/rspec-its/versions/1.2.0) v1.2.0 depends on any version of `rspec-core` from v3.0.0 up, meaning there shouldn't be a conflict.

I created a [test `Gemfile`](https://gist.github.com/jamesottaway/29de3fe7819edb8d10b1) which proves that the two versions of those two gems are compatible.

You might want to post your `Gemfile` and `Gemfile.lock` to help diagnose why you can't get those two versions to play nicely together.

**Comment by otg-kalex** [comment]
Thanks, I had `gem 'rspec'` in `Gemfile`, that depends on old version.
