### ISSUE TITLE
rspec-its breaking InSpec

### ISSUE THREAD

**Issue by walterdolce** [rspec/rspec-its#44]
Hi,

When I use InSpec's [`parse_config_file` resource](https://www.inspec.io/docs/reference/resources/parse_config_file/) to verify the content of an ini-like config file structured like so:
```
[beaver]
foo: baz

[/var/log/apache2/access.log]
bar: baz
```

And I have the following spec:
```
    describe parse_config_file('/etc/beaver/beaver.conf', {
        assignment_regex: /^\s*([^:]*?)\s*:\s*(.*?)\s*$/,
        comment_character: '#'
    }) do
        its('beaver') {
            should include('foo' => 'baz')
        }

        its('/var/log/apache2/access.log') {
            should include('bar' => 'baz')
        }
    end
```

The following error occurs:
```
∅  undefined method `log' for nil:NilClass
```

I believe this is being caused by this line of code which is splitting the value by dot (`.`):
https://github.com/rspec/rspec-its/blob/master/lib/rspec/its.rb#L113

This is effectively causing InSpec (and any other `rspec` "wrapper" feeding that code path something which includes a dot) to break. Not being a core `rspec` developer I'm not sure how I could contribute to solving this problem via Pull Requests etc.

Any advice would be much appreciated.

Thank you.

**Comment by JonRowe** [comment]
Apologies for the long time taken to come back to you on this, to fix this you'd have to add a way to escape the dot for people using long string keys like this.

**Comment by lavahot** [comment]
This is actually a breaking bug for some of my tests. Any chance you can submit a pull request, @walterdolce ?

**Comment by walterdolce** [comment]
@lavahot done :)

**Comment by walterdolce** [comment]
It's not really a fix. It's actually a new "feature" as my PR above adds the ability to define a `split_attribute_by` option to define how to split attribute names.

Then, within InSpec I do something like this:
```
describe parse_config_file('/etc/beaver/beaver.conf', {
        assignment_regex: /^\s*([^:]*?)\s*:\s*(.*?)\s*$/,
        comment_character: '#',
        split_attribute_by: '#' // skips splitting by dot
    }) do
        its('beaver') {
            should include('foo' => 'baz')
        }

        its('/var/log/apache2/access.log') {
            should include('bar' => 'baz')
        }
    end
```

**Comment by JonRowe** [comment]
Closing as stale, it hasn't had fixes so I assume you've solved this upstream by vendoring / replicating this functionality, its also really out of scope.
