### ISSUE TITLE
its against BasicObject fails to generate description

### ISSUE THREAD

**Issue by dnagir** [rspec/rspec-its#46]
When the subject is a `BasicObject` (which of course doesn't have `respond_to?`, `is_a?` and others) then RSpec (or rspec/its) cannot generate the test description.

Example code:

```ruby
class Foo <BasicObject
  def name; 'hello'; end
end

RSpec.describe Foo do
  its(:name) { is_expected.to eq 'hello' }
end
```

This generates output similar to:

```
 example at .<spec file>:10 (Got an error when generating description from matcher: NoMethodError: undefined method `is_a?' for #<Foo:0x007fcd4c3bd938> -- /.../ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/core_ext/time/calculations.rb:16:in `===')
```

I'm not sure of there's the "right" way to fix this as it is not even possible to use `respond_to?` on the BasicObject.
But worth raising this.

**Comment by JonRowe** [comment]
Apologies for the long time taken to get an answer to this, I feel like this was probably fixed upstream, would you mind re-testing?

**Comment by JonRowe** [comment]
Closing as stale
