### ISSUE TITLE
irb: warn: can't alias context from irb_context.

### ISSUE THREAD

**Issue by jacobjlevine** [rspec/rspec-its#78]
When I run the rails console in my development environment, I get a warning saying `irb: warn: can't alias context from irb_context.` I've isolated it to this gem (currently running 1.3.0). I'm guessing this is related to this previously resolved issue from rspec-rails:

https://github.com/rspec/rspec-rails/issues/1645

**Comment by JonRowe** [comment]
I'd suggest this is because you are requiring `rspec/its` in your development environment and not limiting it to test like `rspec/core`. Unlike `rspec-rails` this gem does not need to be loaded in the development environment, so changing your bundle grouping should remove the warning.

**Comment by jacobjlevine** [comment]
Ah, thanks @JonRowe! I was wondering about that while I was doing my testing. Do you know why rspec-rails needs to be included in the development environment? And why are the other gems you mentioned different?

**Comment by JonRowe** [comment]
>  Do you know why rspec-rails needs to be included in the development environment? 

It doesn't need to be, but you don't get the generators and other nicities if you don't.

> And why are the other gems you mentioned different?

This and rspec-core don't integrate with rails so there is no need to include them in the dev environment.
